/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace org.phybros.thrift
{
  /// <summary>
  /// Game difficulties
  /// </summary>
  public enum Difficulty
  {
    /// <summary>
    /// Players regain health over time, hostile mobs don't spawn,
    /// the hunger bar does not deplete.
    /// </summary>
    PEACEFUL = 0,
    /// <summary>
    /// Hostile mobs spawn, enemies deal less damage than on
    /// normal difficulty, the hunger bar does deplete and starving
    /// deals up to 5 hearts of damage.
    /// </summary>
    EASY = 1,
    /// <summary>
    /// Hostile mobs spawn, enemies deal normal amounts of damage,
    /// the hunger bar does deplete and starving deals up to 9.5
    /// hearts of damage.
    /// </summary>
    NORMAL = 2,
    /// <summary>
    /// Hostile mobs spawn, enemies deal greater damage than on
    /// normal difficulty, the hunger bar does deplete and starving
    /// can kill players.
    /// </summary>
    HARD = 3,
  }
}
