/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace org.phybros.thrift
{
  /// <summary>
  /// All enchantments
  /// </summary>
  public enum Enchantment
  {
    /// <summary>
    /// Protection
    /// </summary>
    PROTECTION_ENVIRONMENTAL = 0,
    /// <summary>
    /// Fire Protection
    /// </summary>
    PROTECTION_FIRE = 1,
    /// <summary>
    /// Feather Falling
    /// </summary>
    PROTECTION_FALL = 2,
    /// <summary>
    /// Blast Protection
    /// </summary>
    PROTECTION_EXPLOSIONS = 3,
    /// <summary>
    /// Projectile Protection
    /// </summary>
    PROTECTION_PROJECTILE = 4,
    /// <summary>
    /// Respiration
    /// </summary>
    OXYGEN = 5,
    /// <summary>
    /// Aqua Afiinity
    /// </summary>
    WATER_WORKER = 6,
    /// <summary>
    /// Sharpness
    /// </summary>
    DAMAGE_ALL = 16,
    /// <summary>
    /// Smite
    /// </summary>
    DAMAGE_UNDEAD = 17,
    /// <summary>
    /// Bane of Arthropods
    /// </summary>
    DAMAGE_ARTHROPODS = 18,
    /// <summary>
    /// Knockback
    /// </summary>
    KNOCKBACK = 19,
    /// <summary>
    /// Fire Aspect
    /// </summary>
    FIRE_ASPECT = 20,
    /// <summary>
    /// Looting
    /// </summary>
    LOOT_BONUS_MOBS = 21,
    /// <summary>
    /// Efficiency
    /// </summary>
    DIG_SPEED = 32,
    /// <summary>
    /// Silk Touch
    /// </summary>
    SILK_TOUCH = 33,
    /// <summary>
    /// Unbreaking
    /// </summary>
    DURABILITY = 34,
    /// <summary>
    /// Fortune
    /// </summary>
    LOOT_BONUS_BLOCKS = 35,
    /// <summary>
    /// Power
    /// </summary>
    ARROW_DAMAGE = 48,
    /// <summary>
    /// Punch
    /// </summary>
    ARROW_KNOCKBACK = 49,
    /// <summary>
    /// Flame
    /// </summary>
    ARROW_FIRE = 50,
    /// <summary>
    /// Infinity
    /// </summary>
    ARROW_INFINITE = 51,
  }
}
