/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace org.phybros.thrift
{
  /// <summary>
  /// Represents various map environment types that a world may be
  /// </summary>
  public enum Environment
  {
    NETHER = 0,
    NORMAL = 1,
    THE_END = 2,
  }
}
