/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace org.phybros.thrift
{
  /// <summary>
  /// Various codes used for catching errors
  /// </summary>
  public enum ErrorCode
  {
    /// <summary>
    /// If a parameter was invalid
    /// </summary>
    INVALID_REQUEST = 0,
    /// <summary>
    /// Authentication failed
    /// </summary>
    INVALID_AUTHSTRING = 1,
    /// <summary>
    /// Requested data could not be found
    /// </summary>
    NOT_FOUND = 2,
    /// <summary>
    /// Something went wrong during a download operation
    /// </summary>
    DOWNLOAD_ERROR = 3,
    /// <summary>
    /// Something went wrong during a file operation
    /// </summary>
    FILE_ERROR = 4,
    /// <summary>
    /// Could not read a file
    /// </summary>
    NO_READ = 5,
  }
}
