/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace org.phybros.thrift
{
  /// <summary>
  /// Valid game modes
  /// </summary>
  public enum GameMode
  {
    /// <summary>
    /// Survival Mode
    /// </summary>
    SURVIVAL = 0,
    /// <summary>
    /// Creative Mode
    /// </summary>
    CREATIVE = 1,
    /// <summary>
    /// Adventure Mode
    /// </summary>
    ADVENTURE = 2,
  }
}
